name: Publish Docker image on every push to master branch

on:
  push:
    branches:
      - test-docker
env:
  OTP_VERSION: '25.2.1'
  ELIXIR_VERSION: '1.14.3'
  NEXT_RELEASE_VERSION: 5.1.1

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.output-step.outputs.release-version }}
      short-sha: ${{ steps.output-step.outputs.short-sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{github.repository}}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Add outputs
        run: |
          echo "::set-output name=release-version::${{ env.NEXT_RELEASE_VERSION }}"
          echo "::set-output name=short-sha::${{ env.SHORT_SHA }}"
        id: output-step

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}:latest
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            DISABLE_READ_API=false
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=

      # - name: Build and push Docker image for frontend
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./docker/Dockerfile
      #     push: true
      #     cache-from: type=registry,ref=tvl-labs/blockscan:buildcache
      #     tags: tvl-labs/blockscan:frontend-main
      #     build-args: |
      #       CACHE_EXCHANGE_RATES_PERIOD=
      #       DISABLE_READ_API=false
      #       DISABLE_WEBAPP=false
      #       DISABLE_WRITE_API=false
      #       CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
      #       WOBSERVER_ENABLED=false
      #       ADMIN_PANEL_ENABLED=false
      #       CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
      #       SESSION_COOKIE_DOMAIN=${{ secrets.FRONTEND_MAIN }}
  # tests:
  #   needs: push_to_registry
  #   uses: tvl-labs/blockscan-ci-cd/.github/workflows/e2e_new.yaml@master
  #   with:
  #     blockscoutImage: tvl-labs/blockscan:${{ needs.push_to_registry.outputs.release-version }}-prerelease-${{ needs.push_to_registry.outputs.short-sha }}
  #     blockscoutIngressHost: e2e-blockscout-$GITHUB_SHA_SHORT
  #     frontendIngressHost: e2e-blockscout-$GITHUB_SHA_SHORT
  #     gethIngressHost: e2e-geth-$GITHUB_SHA_SHORT
  #     scVerifierIngressHost: e2e-sc-verifier-$GITHUB_SHA_SHORT
  #   secrets: inherit
